# [[targets]]
#   name = "production"
#   URL = "s3://benstraw.com?region=us-east-2"
#   cloudFrontDistributionID = "E1J7PVZ8DBPM0V"

# [[matchers]]
#   pattern = "^.+\\.(js|css|svg|ttf|woff|woff2|eot|png|gif|pdf)$"
#   cacheControl = "max-age=630720000, no-transform, public"
#   gzip = true

# [[matchers]]
#   pattern = "^.+\\.(html|xml|json)$"
#   gzip = true
